table Dim_Date
	lineageTag: 2ca48147-094d-4d3c-9e92-819cba4466e9

	column DateKey
		dataType: int64
		isKey
		isHidden
		sourceColumn: DateKey
		summarizeBy: none
		lineageTag: 4b207bf3-fd00-496d-b8bb-19c66b17e282

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		sourceColumn: Date
		summarizeBy: none
		lineageTag: a4b26de5-f29d-4c96-b440-f40283492086

	column CalendarYear
		dataType: int64
		sourceColumn: CalendarYear
		summarizeBy: none
		lineageTag: 98cbd2e0-b333-416c-b71b-8ddd1d446b51

	column CalendarMonth
		dataType: int64
		sourceColumn: CalendarMonth
		summarizeBy: none
		lineageTag: 078198ad-b1ba-4bcf-8e88-8e0a24b14a42

	column CalendarMonthName
		dataType: string
		sourceColumn: CalendarMonthName
		summarizeBy: none
		sortByColumn: CalendarMonth
		lineageTag: 20459353-a0b6-456d-a511-41261ebf72c0

	column CalendarQuarter
		dataType: int64
		sourceColumn: CalendarQuarter
		summarizeBy: none
		lineageTag: 007a5bbd-e991-4362-8b6e-466921227bd0

	column FiscalYear
		dataType: int64
		sourceColumn: FiscalYear
		summarizeBy: none
		lineageTag: 32c52298-f43b-4105-ba99-fb075b329f20

	column FiscalMonth
		dataType: int64
		sourceColumn: FiscalMonth
		summarizeBy: none
		lineageTag: ee45696c-07f1-4a81-8cf3-3074d4336971

	column FiscalMonthName
		dataType: string
		sourceColumn: FiscalMonthName
		summarizeBy: none
		sortByColumn: FiscalMonth
		lineageTag: 313044fb-f798-47da-9995-c3566463fd42

	column FiscalQuarter
		dataType: int64
		sourceColumn: FiscalQuarter
		summarizeBy: none
		lineageTag: 289de49f-c561-429e-9bb9-73bfbd2874df

	column IsCurrentFY
		dataType: boolean
		sourceColumn: IsCurrentFY
		summarizeBy: none
		lineageTag: 78d86d8e-df42-4e09-b0b6-3fac5e227dc2

	column IsWeekend
		dataType: boolean
		sourceColumn: IsWeekend
		summarizeBy: none
		lineageTag: e299c853-018d-4713-9347-1d427fe53cb0

	column DayOfWeek
		dataType: int64
		sourceColumn: DayOfWeek
		summarizeBy: none
		lineageTag: 5c55222c-bffc-4789-837c-1e2a2f786ce5

	column DayName
		dataType: string
		sourceColumn: DayName
		summarizeBy: none
		sortByColumn: DayOfWeek
		lineageTag: 7064fd45-906b-4c90-b00f-d00664322bcf

	partition Dim_Date = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("c:\Users\andrea.natali\OneDrive - Avanade\Documents\Progetti\Avanade\Repos\aisemanticlayer\PBIP\data\dim_date.csv"), [Delimiter = ",", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"DateKey", Int64.Type}, 
					{"Date", type datetime}, 
					{"CalendarYear", Int64.Type}, 
					{"CalendarMonth", Int64.Type}, 
					{"CalendarMonthName", type text}, 
					{"CalendarQuarter", Int64.Type}, 
					{"FiscalYear", Int64.Type}, 
					{"FiscalMonth", Int64.Type}, 
					{"FiscalMonthName", type text}, 
					{"FiscalQuarter", Int64.Type}, 
					{"IsCurrentFY", type logical}, 
					{"IsWeekend", type logical}, 
					{"DayOfWeek", Int64.Type}, 
					{"DayName", type text}
				})
			in
				ChangedTypes

