table Dim_Country
	lineageTag: f47c9533-e4f0-4955-9946-2d802f8813fc

	column CountryKey
		dataType: int64
		isKey
		isHidden
		sourceColumn: CountryKey
		summarizeBy: none
		lineageTag: e76fc0ee-8deb-4bbd-a78a-b8f9bad0461f

	column CountryName
		dataType: string
		sourceColumn: CountryName
		summarizeBy: none
		lineageTag: 36ac05f8-b783-4bd6-b5af-fc31db11eea9

	column AreaKey
		dataType: int64
		isHidden
		sourceColumn: AreaKey
		summarizeBy: none
		lineageTag: ff9cffff-550c-477a-b803-d7a3374bf033

	partition Dim_Country = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("c:\Users\andrea.natali\OneDrive - Avanade\Documents\Progetti\Avanade\Repos\aisemanticlayer\PBIP\data\dim_country.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"CountryKey", Int64.Type}, 
					{"CountryName", type text}, 
					{"AreaKey", Int64.Type}
				})
			in
				ChangedTypes

