table Fact_Budget
	lineageTag: d4e09911-c92f-49d7-aecc-c3846c8f7293

	column BudgetKey
		dataType: int64
		isHidden
		sourceColumn: BudgetKey
		summarizeBy: none
		lineageTag: 11fd7045-8687-44be-963c-27b5b8f35e63

	column DateKey
		dataType: int64
		isHidden
		sourceColumn: DateKey
		summarizeBy: none
		lineageTag: ebb0c8a9-2c88-4f41-a718-991fdfb9ff37

	column AreaKey
		dataType: int64
		isHidden
		sourceColumn: AreaKey
		summarizeBy: none
		lineageTag: 7be8902f-5e58-412b-934d-a834181fee02

	column IndustryKey
		dataType: int64
		isHidden
		sourceColumn: IndustryKey
		summarizeBy: none
		lineageTag: 87ca19ea-f400-4b29-80f3-686e39136322

	column 'Budget Amount LC'
		dataType: decimal
		formatString: #,##0.00
		sourceColumn: BudgetAmountLC
		summarizeBy: none
		lineageTag: 70deedd9-d16c-417a-aefe-38a44c91c7cc

	partition Fact_Budget = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("c:\Users\andrea.natali\OneDrive - Avanade\Documents\Progetti\Avanade\Repos\aisemanticlayer\PBIP\data\fact_budget.csv"), [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"BudgetKey", Int64.Type}, 
					{"DateKey", Int64.Type}, 
					{"AreaKey", Int64.Type}, 
					{"IndustryKey", Int64.Type}, 
					{"BudgetAmountLC", type number}
				})
			in
				ChangedTypes

