table Dim_Customer
	lineageTag: 677209d7-7659-4141-b9a9-b8e2c2bba0d4

	column CustomerKey
		dataType: int64
		isKey
		isHidden
		sourceColumn: CustomerKey
		summarizeBy: none
		lineageTag: d6163029-9ab9-4d15-9afd-030452a1694d

	column CustomerName
		dataType: string
		sourceColumn: CustomerName
		summarizeBy: none
		lineageTag: 92d35a14-e3ec-48b9-b381-64f098a06b89

	column CountryKey
		dataType: int64
		isHidden
		sourceColumn: CountryKey
		summarizeBy: none
		lineageTag: 7daed2dd-1bc0-4e52-b60b-29d44fa3da95

	column IndustryKey
		dataType: int64
		isHidden
		sourceColumn: IndustryKey
		summarizeBy: none
		lineageTag: 6f89dd91-af97-48d3-b2b8-cec7336c0c4e

	partition Dim_Customer = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("c:\Users\andrea.natali\OneDrive - Avanade\Documents\Progetti\Avanade\Repos\aisemanticlayer\SalesOverviewFYTD\data\dim_customer.csv"), [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"CustomerKey", Int64.Type}, 
					{"CustomerName", type text}, 
					{"CountryKey", Int64.Type}, 
					{"IndustryKey", Int64.Type}
				})
			in
				ChangedTypes

