table Parameters
	lineageTag: 6ad36644-eab5-4053-a3d7-cab91f2f2d01

	column ParameterName
		dataType: string
		sourceColumn: ParameterName
		summarizeBy: none
		lineageTag: 415efe63-029b-455e-a9b4-f5de0c7cee0c

	column ParameterValue
		dataType: string
		sourceColumn: ParameterValue
		summarizeBy: none
		lineageTag: e8d8d80f-8268-4efc-91e6-d6ce2ac5090d

	partition Parameters = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents("c:\Users\andrea.natali\OneDrive - Avanade\Documents\Progetti\Avanade\Repos\aisemanticlayer\SalesOverviewFYTD\data\parameters.csv"), [Delimiter = ",", Columns = 2, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
				PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {
					{"ParameterName", type text}, 
					{"ParameterValue", type text}
				})
			in
				ChangedTypes

