table Dim_Customer
	lineageTag: 9a1a3757-001a-4b4c-932e-b49575e1a387

	column CustomerKey
		dataType: int64
		isHidden
		isKey
		isAvailableInMdx: false
		lineageTag: ea547e1d-d1d6-49ff-97fb-83c2734f4a29
		summarizeBy: none
		sourceColumn: CustomerKey

	column CustomerName
		dataType: string
		lineageTag: 4580fdf1-9567-4bf9-92ad-3957083ae757
		summarizeBy: none
		sourceColumn: CustomerName

	column Country
		dataType: string
		lineageTag: 3da30cac-bd53-44da-8a2e-2db51bffb2eb
		summarizeBy: none
		sourceColumn: Country

	partition Dim_Customer = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\dim_customer.csv"), [Delimiter = ",", Columns = 3, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"CustomerKey", Int64.Type}, {"CustomerName", type text}, {"Country", type text}})
				in
					ChangedTypes

