table Dim_Industry
	lineageTag: 457f9bd7-2f04-496a-bbe9-db69e3357a4b

	column IndustryKey
		dataType: int64
		isHidden
		isKey
		isAvailableInMdx: false
		lineageTag: d04db555-e7ff-4a8a-95dd-47d68a22deb5
		summarizeBy: none
		sourceColumn: IndustryKey

	column IndustryName
		dataType: string
		lineageTag: a2b0d76d-0335-4d71-8ff8-a0e87c614b46
		summarizeBy: none
		sourceColumn: IndustryName

	partition Dim_Industry = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\dim_industry.csv"), [Delimiter = ",", Columns = 2, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"IndustryKey", Int64.Type}, {"IndustryName", type text}})
				in
					ChangedTypes

