table Dim_Date
	lineageTag: d589f22b-3306-4ccb-a899-54dda58854cb

	column DateKey
		dataType: int64
		isHidden
		isKey
		isAvailableInMdx: false
		lineageTag: 0018054e-62e2-4f76-b403-7a6d9b19b874
		summarizeBy: none
		sourceColumn: DateKey

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 1cff53ac-5f07-4ca9-b6e9-3aaf407e0aef
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 142c333f-9ae1-408f-a3c9-a9785604bab9
			defaultHierarchy: LocalDateTable_da935fe2-0924-4f46-8e26-5b36b783f218.'Date Hierarchy'

	column CalendarYear
		dataType: int64
		formatString: #,##0
		lineageTag: 925a1ed8-e005-40f5-be5f-f28cf19b536f
		summarizeBy: sum
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarMonth
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: 9ec05187-418c-4ce4-8883-f65f25deadca
		summarizeBy: sum
		sourceColumn: CalendarMonth

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5aa66f10-ba49-4f7f-9bde-31aec0874294
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: CalendarMonth

	column CalendarQuarter
		dataType: string
		lineageTag: 6882e1e9-3563-44c1-b906-431ed48884ef
		summarizeBy: none
		sourceColumn: CalendarQuarter

	column FiscalYear
		dataType: string
		lineageTag: 72ef8776-5092-42a2-8c30-5afee1c47def
		summarizeBy: none
		sourceColumn: FiscalYear

	column FiscalMonthNumber
		dataType: int64
		isHidden
		formatString: #,##0
		lineageTag: b5502330-f181-4750-9543-2ae24c727658
		summarizeBy: sum
		sourceColumn: FiscalMonthNumber

		annotation SummarizationSetBy = Automatic

	column FiscalMonth
		dataType: string
		lineageTag: 2e24cc82-d846-460d-9f75-c3976c51157c
		summarizeBy: none
		sourceColumn: FiscalMonth
		sortByColumn: FiscalMonthNumber

	column FiscalQuarter
		dataType: string
		lineageTag: d99174ee-bb28-4c2e-a3cc-8aedf1b4236a
		summarizeBy: none
		sourceColumn: FiscalQuarter

	column FiscalYearMonth
		dataType: string
		lineageTag: e5dcbf5e-54d2-44d4-89bb-84cc344e5108
		summarizeBy: none
		sourceColumn: FiscalYearMonth

	column IsWeekend
		dataType: boolean
		lineageTag: 6db7aaf1-c32c-401c-96c4-fef2e6339444
		summarizeBy: none
		sourceColumn: IsWeekend

	partition Dim_Date = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\dim_date.csv"), [Delimiter = ",", Columns = 12, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"DateKey", Int64.Type}, {"Date", type datetime}, {"CalendarYear", Int64.Type}, {"CalendarMonth", Int64.Type}, {"MonthName", type text}, {"CalendarQuarter", type text}, {"FiscalYear", type text}, {"FiscalMonthNumber", Int64.Type}, {"FiscalMonth", type text}, {"FiscalQuarter", type text}, {"FiscalYearMonth", type text}, {"IsWeekend", type logical}})
				in
					ChangedTypes

