table Dim_Area
	lineageTag: 01cbea75-5ac9-4943-adb0-a01b550fad54

	column AreaKey
		dataType: int64
		isHidden
		isKey
		isAvailableInMdx: false
		lineageTag: deb51ced-41bc-4a4e-b928-799bc4ceb5b5
		summarizeBy: none
		sourceColumn: AreaKey

	column AreaName
		dataType: string
		lineageTag: 3aefcabd-8064-4307-b669-cbb198de7a53
		summarizeBy: none
		sourceColumn: AreaName

	partition Dim_Area = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\dim_area.csv"), [Delimiter = ",", Columns = 2, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"AreaKey", Int64.Type}, {"AreaName", type text}})
				in
					ChangedTypes

