table Fact_Budget
	lineageTag: 572e7405-2f0a-4cfd-9bbb-90365832e340

	column DateKey
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: 1915ff9d-19b8-4148-83b3-2212678d79fe
		summarizeBy: none
		sourceColumn: DateKey

	column AreaKey
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: b2280867-5de6-40d4-9041-807db4642d00
		summarizeBy: none
		sourceColumn: AreaKey

	column IndustryKey
		dataType: int64
		isHidden
		isAvailableInMdx: false
		lineageTag: cb114b75-134d-40f8-84a4-fb7ea571d75e
		summarizeBy: none
		sourceColumn: IndustryKey

	column BudgetAmountLC
		dataType: double
		formatString: #,##0.00
		lineageTag: 55588441-b9e3-42fb-9353-58b240abe9ea
		summarizeBy: sum
		sourceColumn: BudgetAmountLC

		annotation SummarizationSetBy = Automatic

	partition Fact_Budget = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(DataPath & "\fact_budget.csv"), [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.None]),
					PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
					ChangedTypes = Table.TransformColumnTypes(PromotedHeaders, {{"DateKey", Int64.Type}, {"AreaKey", Int64.Type}, {"IndustryKey", Int64.Type}, {"BudgetAmountLC", type number}})
				in
					ChangedTypes

